// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#ifndef _ENVIRONMENT_SENSOR_UI_H
#define _ENVIRONMENT_SENSOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_TemperatureGroup;
extern lv_obj_t * ui_TemperatureArc;
extern lv_obj_t * ui_Thermometer;
extern lv_obj_t * ui_TemperatureLabel;
extern lv_obj_t * ui_HumidityGroup;
extern lv_obj_t * ui_HumidityArc;
extern lv_obj_t * ui_Droplet;
extern lv_obj_t * ui_DropletLabel;
extern lv_obj_t * ui_CO2Group;
extern lv_obj_t * ui_CO2Arc;
extern lv_obj_t * ui_CO2;
extern lv_obj_t * ui_CO2Label;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_blue_yellow_red2_png);    // assets\blue_yellow_red2.png
LV_IMG_DECLARE(ui_img_thermometer_png);    // assets\Thermometer.png
LV_IMG_DECLARE(ui_img_water_png);    // assets\Water.png
LV_IMG_DECLARE(ui_img_droplet_png);    // assets\Droplet.png
LV_IMG_DECLARE(ui_img_co2_arc_png);    // assets\co2_arc.png
LV_IMG_DECLARE(ui_img_co2_png);    // assets\co2.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
