// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "../ui.h"

void ui_PasswordScreen_screen_init(void)
{
    ui_PasswordScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PasswordScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PasswordKeyboard = lv_keyboard_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordKeyboard, 300);
    lv_obj_set_height(ui_PasswordKeyboard, 120);
    lv_obj_set_x(ui_PasswordKeyboard, 0);
    lv_obj_set_y(ui_PasswordKeyboard, -19);
    lv_obj_set_align(ui_PasswordKeyboard, LV_ALIGN_CENTER);

    ui_PasswordTextArea = lv_textarea_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordTextArea, 246);
    lv_obj_set_height(ui_PasswordTextArea, 36);
    lv_obj_set_x(ui_PasswordTextArea, -25);
    lv_obj_set_y(ui_PasswordTextArea, 63);
    lv_obj_set_align(ui_PasswordTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PasswordTextArea, "Placeholder...");

    ui_PasswordConfirmButton = lv_btn_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordConfirmButton, 50);
    lv_obj_set_height(ui_PasswordConfirmButton, 36);
    lv_obj_set_x(ui_PasswordConfirmButton, 125);
    lv_obj_set_y(ui_PasswordConfirmButton, 63);
    lv_obj_set_align(ui_PasswordConfirmButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PasswordConfirmButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PasswordConfirmButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PasswordConfirmButton, lv_color_hex(0x22BA45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PasswordConfirmButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PasswordConfirmButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PasswordConfirmButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 124);
    lv_obj_set_y(ui_Label1, 64);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "OK");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PasswordKeyboard, ui_event_PasswordKeyboard, LV_EVENT_ALL, NULL);

}
