// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "../ui.h"

void ui_TemperatureScreen1_screen_init(void)
{
    ui_TemperatureScreen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TemperatureScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_TemperatureScreen1, &ui_img_main_screen_gradient3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureLabel2 = lv_label_create(ui_TemperatureScreen1);
    lv_obj_set_width(ui_TemperatureLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureLabel2, 52);
    lv_obj_set_y(ui_TemperatureLabel2, -59);
    lv_obj_set_align(ui_TemperatureLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureLabel2, "Temperature");
    lv_obj_set_style_text_color(ui_TemperatureLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureLabel2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThermometerIcon2 = lv_img_create(ui_TemperatureScreen1);
    lv_img_set_src(ui_ThermometerIcon2, &ui_img_thermometer2_png);
    lv_obj_set_width(ui_ThermometerIcon2, LV_SIZE_CONTENT);   /// 106
    lv_obj_set_height(ui_ThermometerIcon2, LV_SIZE_CONTENT);    /// 102
    lv_obj_set_x(ui_ThermometerIcon2, 15);
    lv_obj_set_y(ui_ThermometerIcon2, 29);
    lv_obj_set_align(ui_ThermometerIcon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ThermometerIcon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ThermometerIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempValue1 = lv_label_create(ui_TemperatureScreen1);
    lv_obj_set_width(ui_TempValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempValue1, -107);
    lv_obj_set_y(ui_TempValue1, 11);
    lv_obj_set_align(ui_TempValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempValue1, "+25");
    lv_obj_set_style_text_color(ui_TempValue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempValue1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeIcon1 = lv_img_create(ui_TemperatureScreen1);
    lv_img_set_src(ui_HomeIcon1, &ui_img_home_png);
    lv_obj_set_width(ui_HomeIcon1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_HomeIcon1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_HomeIcon1, 106);
    lv_obj_set_y(ui_HomeIcon1, 28);
    lv_obj_set_align(ui_HomeIcon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_TemperatureScreen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -87);
    lv_obj_set_y(ui_Label2, 57);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Indoor");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_TemperatureScreen1);
    lv_img_set_src(ui_Image2, &ui_img_menu_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -116);
    lv_obj_set_y(ui_Image2, -54);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThermometerIcon3 = lv_img_create(ui_TemperatureScreen1);
    lv_img_set_src(ui_ThermometerIcon3, &ui_img_thermometer2_png);
    lv_obj_set_width(ui_ThermometerIcon3, LV_SIZE_CONTENT);   /// 106
    lv_obj_set_height(ui_ThermometerIcon3, LV_SIZE_CONTENT);    /// 102
    lv_obj_set_x(ui_ThermometerIcon3, 15);
    lv_obj_set_y(ui_ThermometerIcon3, 29);
    lv_obj_set_align(ui_ThermometerIcon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ThermometerIcon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ThermometerIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
