// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "../ui.h"

void ui_TemperatureScreen2_screen_init(void)
{
    ui_TemperatureScreen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TemperatureScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_TemperatureScreen2, &ui_img_yellow_dithered_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureLabel3 = lv_label_create(ui_TemperatureScreen2);
    lv_obj_set_width(ui_TemperatureLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureLabel3, 52);
    lv_obj_set_y(ui_TemperatureLabel3, -59);
    lv_obj_set_align(ui_TemperatureLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureLabel3, "Temperature");
    lv_obj_set_style_text_color(ui_TemperatureLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureLabel3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThermometerIcon4 = lv_img_create(ui_TemperatureScreen2);
    lv_img_set_src(ui_ThermometerIcon4, &ui_img_thermometer2_png);
    lv_obj_set_width(ui_ThermometerIcon4, LV_SIZE_CONTENT);   /// 106
    lv_obj_set_height(ui_ThermometerIcon4, LV_SIZE_CONTENT);    /// 102
    lv_obj_set_x(ui_ThermometerIcon4, 15);
    lv_obj_set_y(ui_ThermometerIcon4, 29);
    lv_obj_set_align(ui_ThermometerIcon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ThermometerIcon4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ThermometerIcon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempValue2 = lv_label_create(ui_TemperatureScreen2);
    lv_obj_set_width(ui_TempValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempValue2, -107);
    lv_obj_set_y(ui_TempValue2, 11);
    lv_obj_set_align(ui_TempValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempValue2, "+25");
    lv_obj_set_style_text_color(ui_TempValue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempValue2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeIcon2 = lv_img_create(ui_TemperatureScreen2);
    lv_img_set_src(ui_HomeIcon2, &ui_img_home_png);
    lv_obj_set_width(ui_HomeIcon2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_HomeIcon2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_HomeIcon2, 106);
    lv_obj_set_y(ui_HomeIcon2, 28);
    lv_obj_set_align(ui_HomeIcon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeIcon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_TemperatureScreen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -87);
    lv_obj_set_y(ui_Label3, 57);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Indoor");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_TemperatureScreen2);
    lv_img_set_src(ui_Image3, &ui_img_menu_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -116);
    lv_obj_set_y(ui_Image3, -54);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThermometerIcon5 = lv_img_create(ui_TemperatureScreen2);
    lv_img_set_src(ui_ThermometerIcon5, &ui_img_thermometer2_png);
    lv_obj_set_width(ui_ThermometerIcon5, LV_SIZE_CONTENT);   /// 106
    lv_obj_set_height(ui_ThermometerIcon5, LV_SIZE_CONTENT);    /// 102
    lv_obj_set_x(ui_ThermometerIcon5, 15);
    lv_obj_set_y(ui_ThermometerIcon5, 29);
    lv_obj_set_align(ui_ThermometerIcon5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ThermometerIcon5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ThermometerIcon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
