// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "../ui.h"

void ui_TemperatureScreen_screen_init(void)
{
    ui_TemperatureScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TemperatureScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_TemperatureScreen, &ui_img_main_screen_gradient3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureLabel = lv_label_create(ui_TemperatureScreen);
    lv_obj_set_width(ui_TemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureLabel, 30);
    lv_obj_set_y(ui_TemperatureLabel, -55);
    lv_obj_set_align(ui_TemperatureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureLabel, "Temperature");
    lv_obj_set_style_text_color(ui_TemperatureLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempValue = lv_label_create(ui_TemperatureScreen);
    lv_obj_set_width(ui_TempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempValue, -100);
    lv_obj_set_y(ui_TempValue, 20);
    lv_obj_set_align(ui_TempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempValue, "+25.2");
    lv_obj_set_style_text_color(ui_TempValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeIcon2 = lv_img_create(ui_TemperatureScreen);
    lv_img_set_src(ui_HomeIcon2, &ui_img_home_png);
    lv_obj_set_width(ui_HomeIcon2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_HomeIcon2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_HomeIcon2, 106);
    lv_obj_set_y(ui_HomeIcon2, 28);
    lv_obj_set_align(ui_HomeIcon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeIcon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PlaceIcon2 = lv_label_create(ui_TemperatureScreen);
    lv_obj_set_width(ui_PlaceIcon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlaceIcon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlaceIcon2, -100);
    lv_obj_set_y(ui_PlaceIcon2, 60);
    lv_obj_set_align(ui_PlaceIcon2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlaceIcon2, "Indoor");
    lv_obj_set_style_text_color(ui_PlaceIcon2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlaceIcon2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlaceIcon2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuIcon2 = lv_img_create(ui_TemperatureScreen);
    lv_img_set_src(ui_MenuIcon2, &ui_img_menu_png);
    lv_obj_set_width(ui_MenuIcon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuIcon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuIcon2, -120);
    lv_obj_set_y(ui_MenuIcon2, -50);
    lv_obj_set_align(ui_MenuIcon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuIcon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MenuIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThermometerIcon = lv_img_create(ui_TemperatureScreen);
    lv_img_set_src(ui_ThermometerIcon, &ui_img_thermometer2_png);
    lv_obj_set_width(ui_ThermometerIcon, LV_SIZE_CONTENT);   /// 106
    lv_obj_set_height(ui_ThermometerIcon, LV_SIZE_CONTENT);    /// 102
    lv_obj_set_x(ui_ThermometerIcon, 25);
    lv_obj_set_y(ui_ThermometerIcon, 35);
    lv_obj_set_align(ui_ThermometerIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ThermometerIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ThermometerIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ThermometerIcon, 200);

}
