// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#ifndef _ENVIRONMENT_SENSOR_UI_H
#define _ENVIRONMENT_SENSOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Icon_group;
extern lv_obj_t * ui_Droplet;
extern lv_obj_t * ui_Thermometer;
extern lv_obj_t * ui_Text_group;
extern lv_obj_t * ui_TemperatureText;
extern lv_obj_t * ui_HumidityText;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_droplet_png);    // assets\Droplet.png
LV_IMG_DECLARE(ui_img_thermometer_png);    // assets\Thermometer.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
