// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_MainMenu
void ui_MainMenu_screen_init(void);
lv_obj_t * ui_MainMenu;
lv_obj_t * ui_WiFiStatusLabel;
lv_obj_t * ui_IndoorLabel;
lv_obj_t * ui_IndoorLabel1;
void ui_event_Image1(lv_event_t * e);
lv_obj_t * ui_Image1;

// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t * ui_SettingsScreen;
void ui_event_Dropdown2(lv_event_t * e);
lv_obj_t * ui_Dropdown2;
lv_obj_t * ui_SettingMenu;

// SCREEN: ui_HumidityScreen
void ui_HumidityScreen_screen_init(void);
lv_obj_t * ui_HumidityScreen;
lv_obj_t * ui_HumidityLabel;
lv_obj_t * ui_DropletIcon;
lv_obj_t * ui_HumidityValue;
lv_obj_t * ui_HomeIcon;
lv_obj_t * ui_PlaceIcon;
void ui_event_MenuIcon(lv_event_t * e);
lv_obj_t * ui_MenuIcon;

// SCREEN: ui_TemperatureScreen
void ui_TemperatureScreen_screen_init(void);
lv_obj_t * ui_TemperatureScreen;
lv_obj_t * ui_TemperatureLabel;
lv_obj_t * ui_TempValue;
lv_obj_t * ui_HomeIcon2;
lv_obj_t * ui_PlaceIcon2;
lv_obj_t * ui_MenuIcon2;
lv_obj_t * ui_ThermometerIcon;

// SCREEN: ui_CO2Screen
void ui_CO2Screen_screen_init(void);
lv_obj_t * ui_CO2Screen;
lv_obj_t * ui_CO2Label;
lv_obj_t * ui_CO2Icon;
lv_obj_t * ui_CO2Value;
lv_obj_t * ui_HomeIcon3;
lv_obj_t * ui_PlaceLabel3;
lv_obj_t * ui_MenuIcon3;

// SCREEN: ui_PasswordScreen
void ui_PasswordScreen_screen_init(void);
lv_obj_t * ui_PasswordScreen;
void ui_event_PasswordKeyboard(lv_event_t * e);
lv_obj_t * ui_PasswordKeyboard;
lv_obj_t * ui_PasswordTextArea;
lv_obj_t * ui_PasswordConfirmButton;
lv_obj_t * ui_Label1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_main_screen_gradient[1] = {&ui_img_main_screen_gradient3_png};
const lv_img_dsc_t * ui_imgset_thermometer[1] = {&ui_img_thermometer2_png};
const lv_img_dsc_t * ui_imgset_droplet[1] = {&ui_img_droplet2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_Dropdown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_screen_change(ui_PasswordScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_MenuIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_TemperatureScreen, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0);
    }
}
void ui_event_PasswordKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_PasswordScreen,  ui_PasswordTextArea);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainMenu_screen_init();
    ui_SettingsScreen_screen_init();
    ui_HumidityScreen_screen_init();
    ui_TemperatureScreen_screen_init();
    ui_CO2Screen_screen_init();
    ui_PasswordScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainMenu);
}
