// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#ifndef _ENVIRONMENT_SENSOR_UI_H
#define _ENVIRONMENT_SENSOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_MainMenu
void ui_MainMenu_screen_init(void);
extern lv_obj_t * ui_MainMenu;
extern lv_obj_t * ui_WiFiStatusLabel;
extern lv_obj_t * ui_IndoorLabel;
extern lv_obj_t * ui_IndoorLabel1;
void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t * ui_SettingsScreen;
void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_SettingMenu;
// SCREEN: ui_HumidityScreen
void ui_HumidityScreen_screen_init(void);
extern lv_obj_t * ui_HumidityScreen;
extern lv_obj_t * ui_HumidityLabel;
extern lv_obj_t * ui_DropletIcon;
extern lv_obj_t * ui_HumidityValue;
extern lv_obj_t * ui_HomeIcon;
extern lv_obj_t * ui_PlaceIcon;
void ui_event_MenuIcon(lv_event_t * e);
extern lv_obj_t * ui_MenuIcon;
// SCREEN: ui_TemperatureScreen
void ui_TemperatureScreen_screen_init(void);
extern lv_obj_t * ui_TemperatureScreen;
extern lv_obj_t * ui_TemperatureLabel;
extern lv_obj_t * ui_TempValue;
extern lv_obj_t * ui_HomeIcon2;
extern lv_obj_t * ui_PlaceIcon2;
extern lv_obj_t * ui_MenuIcon2;
extern lv_obj_t * ui_ThermometerIcon;
// SCREEN: ui_CO2Screen
void ui_CO2Screen_screen_init(void);
extern lv_obj_t * ui_CO2Screen;
extern lv_obj_t * ui_CO2Label;
extern lv_obj_t * ui_CO2Icon;
extern lv_obj_t * ui_CO2Value;
extern lv_obj_t * ui_HomeIcon3;
extern lv_obj_t * ui_PlaceLabel3;
extern lv_obj_t * ui_MenuIcon3;
// SCREEN: ui_PasswordScreen
void ui_PasswordScreen_screen_init(void);
extern lv_obj_t * ui_PasswordScreen;
void ui_event_PasswordKeyboard(lv_event_t * e);
extern lv_obj_t * ui_PasswordKeyboard;
extern lv_obj_t * ui_PasswordTextArea;
extern lv_obj_t * ui_PasswordConfirmButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_main_screen_gradient_dithered_png);    // assets\Main_screen_gradient_dithered.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets\Settings.png
LV_IMG_DECLARE(ui_img_light_blue_dithered_png);    // assets\light_blue_dithered.png
LV_IMG_DECLARE(ui_img_droplet2_png);    // assets\Droplet2.png
LV_IMG_DECLARE(ui_img_home_png);    // assets\home.png
LV_IMG_DECLARE(ui_img_menu_png);    // assets\menu.png
LV_IMG_DECLARE(ui_img_main_screen_gradient3_png);    // assets\Main_screen_gradient3.png
LV_IMG_DECLARE(ui_img_thermometer2_png);    // assets\Thermometer2.png
LV_IMG_DECLARE(ui_img_yellow_dithered_png);    // assets\yellow_dithered.png
LV_IMG_DECLARE(ui_img_co2_new_png);    // assets\CO2_new.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
