// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "../ui.h"

void ui_CO2Screen_screen_init(void)
{
    ui_CO2Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CO2Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_CO2Screen, &ui_img_yellow_dithered_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Label = lv_label_create(ui_CO2Screen);
    lv_obj_set_width(ui_CO2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2Label, -38);
    lv_obj_set_y(ui_CO2Label, -57);
    lv_obj_set_align(ui_CO2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2Label, "CO2");
    lv_obj_set_style_text_color(ui_CO2Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2Label, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Icon = lv_img_create(ui_CO2Screen);
    lv_img_set_src(ui_CO2Icon, &ui_img_co2_new_png);
    lv_obj_set_width(ui_CO2Icon, LV_SIZE_CONTENT);   /// 106
    lv_obj_set_height(ui_CO2Icon, LV_SIZE_CONTENT);    /// 102
    lv_obj_set_x(ui_CO2Icon, 25);
    lv_obj_set_y(ui_CO2Icon, 35);
    lv_obj_set_align(ui_CO2Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CO2Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CO2Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CO2Icon, 200);

    ui_CO2Value = lv_label_create(ui_CO2Screen);
    lv_obj_set_width(ui_CO2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2Value, -80);
    lv_obj_set_y(ui_CO2Value, 20);
    lv_obj_set_align(ui_CO2Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2Value, "500ppm");
    lv_obj_set_style_text_color(ui_CO2Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2Value, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeIcon3 = lv_img_create(ui_CO2Screen);
    lv_img_set_src(ui_HomeIcon3, &ui_img_home_png);
    lv_obj_set_width(ui_HomeIcon3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_HomeIcon3, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_HomeIcon3, 106);
    lv_obj_set_y(ui_HomeIcon3, 28);
    lv_obj_set_align(ui_HomeIcon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeIcon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PlaceLabel3 = lv_label_create(ui_CO2Screen);
    lv_obj_set_width(ui_PlaceLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlaceLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlaceLabel3, -80);
    lv_obj_set_y(ui_PlaceLabel3, 60);
    lv_obj_set_align(ui_PlaceLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlaceLabel3, "Indoor");
    lv_obj_set_style_text_color(ui_PlaceLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlaceLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlaceLabel3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuIcon3 = lv_img_create(ui_CO2Screen);
    lv_img_set_src(ui_MenuIcon3, &ui_img_menu_png);
    lv_obj_set_width(ui_MenuIcon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuIcon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuIcon3, -116);
    lv_obj_set_y(ui_MenuIcon3, -54);
    lv_obj_set_align(ui_MenuIcon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuIcon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MenuIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
