// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "../ui.h"

void ui_ConfirmationScreen_screen_init(void)
{
ui_ConfirmationScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ConfirmationScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_ConfirmationScreen, &ui_img_light_blue_dithered_rotated_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_CalibrateInfo = lv_label_create(ui_ConfirmationScreen);
lv_obj_set_width( ui_CalibrateInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CalibrateInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CalibrateInfo, 1 );
lv_obj_set_y( ui_CalibrateInfo, -64 );
lv_obj_set_align( ui_CalibrateInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_CalibrateInfo,"Calibrate in Fresh air:\nTake device outside\nfor a few minutes");
lv_obj_set_style_text_color(ui_CalibrateInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CalibrateInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CalibrateInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CalibrateInfo, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CalibrateStart = lv_btn_create(ui_ConfirmationScreen);
lv_obj_set_width( ui_CalibrateStart, 100);
lv_obj_set_height( ui_CalibrateStart, 50);
lv_obj_set_align( ui_CalibrateStart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CalibrateStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CalibrateStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CalibrateStart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CalibrateStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CalibrateStart, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StartLabel = lv_label_create(ui_ConfirmationScreen);
lv_obj_set_width( ui_StartLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StartLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_StartLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_StartLabel,"Calibrate");
lv_obj_set_style_text_font(ui_StartLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UpdateProgress = lv_bar_create(ui_ConfirmationScreen);
lv_obj_set_width( ui_UpdateProgress, 150);
lv_obj_set_height( ui_UpdateProgress, 20);
lv_obj_set_x( ui_UpdateProgress, 0 );
lv_obj_set_y( ui_UpdateProgress, 70 );
lv_obj_set_align( ui_UpdateProgress, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_UpdateProgress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_UpdateProgress, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_anim_time(ui_UpdateProgress, 5000, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_UpdateProgress, lv_color_hex(0x409E3B), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_UpdateProgress, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_BackButton2 = lv_btn_create(ui_ConfirmationScreen);
lv_obj_set_width( ui_BackButton2, 120);
lv_obj_set_height( ui_BackButton2, 50);
lv_obj_set_x( ui_BackButton2, 0 );
lv_obj_set_y( ui_BackButton2, 130 );
lv_obj_set_align( ui_BackButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BackButton2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BackButton2, lv_color_hex(0xD76565), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BackButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackLabel2 = lv_label_create(ui_ConfirmationScreen);
lv_obj_set_width( ui_BackLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackLabel2, 0 );
lv_obj_set_y( ui_BackLabel2, 130 );
lv_obj_set_align( ui_BackLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackLabel2,"BACK");
lv_obj_set_style_text_color(ui_BackLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackLabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackLabel2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_CalibrateStart, ui_event_CalibrateStart, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackButton2, ui_event_BackButton2, LV_EVENT_ALL, NULL);

}
