// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "../ui.h"

void ui_HumidityScreen_screen_init(void)
{
    ui_HumidityScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HumidityScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_HumidityScreen, &ui_img_light_blue_dithered_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityLabel = lv_label_create(ui_HumidityScreen);
    lv_obj_set_width(ui_HumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityLabel, -2);
    lv_obj_set_y(ui_HumidityLabel, -57);
    lv_obj_set_align(ui_HumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityLabel, "Humidity");
    lv_obj_set_style_text_color(ui_HumidityLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropletIcon = lv_img_create(ui_HumidityScreen);
    lv_img_set_src(ui_DropletIcon, &ui_img_droplet2_png);
    lv_obj_set_width(ui_DropletIcon, LV_SIZE_CONTENT);   /// 106
    lv_obj_set_height(ui_DropletIcon, LV_SIZE_CONTENT);    /// 102
    lv_obj_set_x(ui_DropletIcon, 25);
    lv_obj_set_y(ui_DropletIcon, 35);
    lv_obj_set_align(ui_DropletIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropletIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DropletIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_DropletIcon, 200);

    ui_HumidityValue = lv_label_create(ui_HumidityScreen);
    lv_obj_set_width(ui_HumidityValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityValue, -100);
    lv_obj_set_y(ui_HumidityValue, 20);
    lv_obj_set_align(ui_HumidityValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityValue, "70%");
    lv_obj_set_style_text_color(ui_HumidityValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeIcon = lv_img_create(ui_HumidityScreen);
    lv_img_set_src(ui_HomeIcon, &ui_img_home_png);
    lv_obj_set_width(ui_HomeIcon, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_HomeIcon, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_HomeIcon, 106);
    lv_obj_set_y(ui_HomeIcon, 28);
    lv_obj_set_align(ui_HomeIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PlaceIcon = lv_label_create(ui_HumidityScreen);
    lv_obj_set_width(ui_PlaceIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlaceIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlaceIcon, -100);
    lv_obj_set_y(ui_PlaceIcon, 60);
    lv_obj_set_align(ui_PlaceIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlaceIcon, "Indoor");
    lv_obj_set_style_text_color(ui_PlaceIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlaceIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlaceIcon, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuIcon = lv_img_create(ui_HumidityScreen);
    lv_img_set_src(ui_MenuIcon, &ui_img_menu_png);
    lv_obj_set_width(ui_MenuIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuIcon, -120);
    lv_obj_set_y(ui_MenuIcon, -50);
    lv_obj_set_align(ui_MenuIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MenuIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_MenuIcon, ui_event_MenuIcon, LV_EVENT_ALL, NULL);

}
