// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "../ui.h"

void ui_MainMenu1_screen_init(void)
{
    ui_MainMenu1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainMenu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_MainMenu1, &ui_img_main_screen_gradient_dithered_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiStatusLabel = lv_label_create(ui_MainMenu1);
    lv_obj_set_width(ui_WiFiStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiStatusLabel, -113);
    lv_obj_set_y(ui_WiFiStatusLabel, -63);
    lv_obj_set_align(ui_WiFiStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiStatusLabel, "WiFi:");
    lv_obj_set_style_text_color(ui_WiFiStatusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiStatusLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IndoorLabel = lv_label_create(ui_MainMenu1);
    lv_obj_set_width(ui_IndoorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IndoorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IndoorLabel, -99);
    lv_obj_set_y(ui_IndoorLabel, -26);
    lv_obj_set_align(ui_IndoorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IndoorLabel, "Indoor:");
    lv_obj_set_style_text_color(ui_IndoorLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IndoorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IndoorLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IndoorLabel1 = lv_label_create(ui_MainMenu1);
    lv_obj_set_width(ui_IndoorLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IndoorLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IndoorLabel1, -86);
    lv_obj_set_y(ui_IndoorLabel1, 11);
    lv_obj_set_align(ui_IndoorLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IndoorLabel1, "Outdoor:");
    lv_obj_set_style_text_color(ui_IndoorLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IndoorLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IndoorLabel1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_MainMenu1);
    lv_img_set_src(ui_Image1, &ui_img_settings_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 201
    lv_obj_set_x(ui_Image1, 98);
    lv_obj_set_y(ui_Image1, 14);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 150);

    lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);

}
