// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "../ui.h"

void ui_PasswordScreen_screen_init(void)
{
    ui_PasswordScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PasswordScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard = lv_keyboard_create(ui_PasswordScreen);
    lv_obj_set_width(ui_Keyboard, 320);
    lv_obj_set_height(ui_Keyboard, 125);
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, -20);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_CENTER);

    ui_PasswordTextArea = lv_textarea_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordTextArea, 200);
    lv_obj_set_height(ui_PasswordTextArea, 36);
    lv_obj_set_x(ui_PasswordTextArea, -2);
    lv_obj_set_y(ui_PasswordTextArea, 64);
    lv_obj_set_align(ui_PasswordTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PasswordTextArea, "Placeholder...");

    ui_PasswordConfirmButton = lv_btn_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordConfirmButton, 55);
    lv_obj_set_height(ui_PasswordConfirmButton, 36);
    lv_obj_set_x(ui_PasswordConfirmButton, 129);
    lv_obj_set_y(ui_PasswordConfirmButton, 63);
    lv_obj_set_align(ui_PasswordConfirmButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PasswordConfirmButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PasswordConfirmButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PasswordConfirmButton, lv_color_hex(0x22BA45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PasswordConfirmButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PasswordConfirmButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PasswordConfirmButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordOkLabel = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordOkLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PasswordOkLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PasswordOkLabel, 131);
    lv_obj_set_y(ui_PasswordOkLabel, 64);
    lv_obj_set_align(ui_PasswordOkLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PasswordOkLabel, "OK");
    lv_obj_set_style_text_color(ui_PasswordOkLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PasswordOkLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordReturnButton = lv_btn_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordReturnButton, 55);
    lv_obj_set_height(ui_PasswordReturnButton, 36);
    lv_obj_set_x(ui_PasswordReturnButton, -132);
    lv_obj_set_y(ui_PasswordReturnButton, 64);
    lv_obj_set_align(ui_PasswordReturnButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PasswordReturnButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PasswordReturnButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PasswordReturnButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PasswordReturnButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PasswordReturnButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PasswordReturnButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordReturnLabel = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordReturnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PasswordReturnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PasswordReturnLabel, -133);
    lv_obj_set_y(ui_PasswordReturnLabel, 64);
    lv_obj_set_align(ui_PasswordReturnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PasswordReturnLabel, "Return");
    lv_obj_set_style_text_color(ui_PasswordReturnLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PasswordReturnLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_Keyboard, ui_PasswordTextArea);

}
