// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "../ui.h"

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_SettingsScreen, &ui_img_main_screen_gradient_dithered_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Dropdown2, 150);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, -68);
    lv_obj_set_y(ui_Dropdown2, -9);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SettingMenu = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_SettingMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingMenu, -51);
    lv_obj_set_y(ui_SettingMenu, -61);
    lv_obj_set_align(ui_SettingMenu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingMenu, "WiFi settings");
    lv_obj_set_style_text_color(ui_SettingMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingMenu, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);

}
