// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "ui.h"

void ui_CalibrationScreen_screen_init(void)
{
ui_CalibrationScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_CalibrationScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_CalibrationScreen, &ui_img_light_blue_dithered_rotated_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_CalibrateLabel = lv_label_create(ui_CalibrationScreen);
lv_obj_set_width( ui_CalibrateLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CalibrateLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CalibrateLabel, 0 );
lv_obj_set_y( ui_CalibrateLabel, -48 );
lv_obj_set_align( ui_CalibrateLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CalibrateLabel,"Calibrate CO2");
lv_obj_set_style_text_color(ui_CalibrateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CalibrateLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CalibrateLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CalibrateLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CalibrateButton = lv_imgbtn_create(ui_CalibrationScreen);
lv_imgbtn_set_src(ui_CalibrateButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_calibrate_png, NULL);
lv_obj_set_height( ui_CalibrateButton, 80);
lv_obj_set_width( ui_CalibrateButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_CalibrateButton, 1 );
lv_obj_set_y( ui_CalibrateButton, 23 );
lv_obj_set_align( ui_CalibrateButton, LV_ALIGN_CENTER );

ui_BackButton1 = lv_btn_create(ui_CalibrationScreen);
lv_obj_set_width( ui_BackButton1, 120);
lv_obj_set_height( ui_BackButton1, 50);
lv_obj_set_x( ui_BackButton1, 0 );
lv_obj_set_y( ui_BackButton1, 130 );
lv_obj_set_align( ui_BackButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BackButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BackButton1, lv_color_hex(0xD76565), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BackButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackLabel1 = lv_label_create(ui_CalibrationScreen);
lv_obj_set_width( ui_BackLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackLabel1, 0 );
lv_obj_set_y( ui_BackLabel1, 130 );
lv_obj_set_align( ui_BackLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackLabel1,"BACK");
lv_obj_set_style_text_color(ui_BackLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackLabel1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_CalibrateButton, ui_event_CalibrateButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackButton1, ui_event_BackButton1, LV_EVENT_ALL, NULL);

}
