// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TemperatureGroup = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_TemperatureGroup, 160);
    lv_obj_set_height(ui_TemperatureGroup, 100);
    lv_obj_set_x(ui_TemperatureGroup, 0);
    lv_obj_set_y(ui_TemperatureGroup, -100);
    lv_obj_set_align(ui_TemperatureGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TemperatureGroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TemperatureGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureGroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TemperatureGroup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TemperatureGroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureArc = lv_arc_create(ui_TemperatureGroup);
    lv_obj_set_width(ui_TemperatureArc, 80);
    lv_obj_set_height(ui_TemperatureArc, 80);
    lv_obj_set_x(ui_TemperatureArc, -40);
    lv_obj_set_y(ui_TemperatureArc, 0);
    lv_obj_set_align(ui_TemperatureArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_TemperatureArc, -40, 100);
    lv_arc_set_value(ui_TemperatureArc, 55);
    lv_obj_set_style_arc_color(ui_TemperatureArc, lv_color_hex(0xB3B3E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TemperatureArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TemperatureArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_TemperatureArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_TemperatureArc, &ui_img_blue_yellow_red2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Thermometer = lv_img_create(ui_TemperatureGroup);
    lv_img_set_src(ui_Thermometer, &ui_img_thermometer_png);
    lv_obj_set_width(ui_Thermometer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thermometer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thermometer, -40);
    lv_obj_set_y(ui_Thermometer, 0);
    lv_obj_set_align(ui_Thermometer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Thermometer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Thermometer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Thermometer, 100);

    ui_TemperatureLabel = lv_label_create(ui_TemperatureGroup);
    lv_obj_set_width(ui_TemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureLabel, 40);
    lv_obj_set_y(ui_TemperatureLabel, 0);
    lv_obj_set_align(ui_TemperatureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureLabel, "+24.5°");
    lv_obj_set_style_text_font(ui_TemperatureLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityGroup = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_HumidityGroup, 160);
    lv_obj_set_height(ui_HumidityGroup, 100);
    lv_obj_set_align(ui_HumidityGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumidityGroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HumidityGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumidityGroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HumidityGroup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HumidityGroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityArc = lv_arc_create(ui_HumidityGroup);
    lv_obj_set_width(ui_HumidityArc, 80);
    lv_obj_set_height(ui_HumidityArc, 80);
    lv_obj_set_x(ui_HumidityArc, -40);
    lv_obj_set_y(ui_HumidityArc, 0);
    lv_obj_set_align(ui_HumidityArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_HumidityArc, 55);
    lv_obj_set_style_arc_color(ui_HumidityArc, lv_color_hex(0xB3B3E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_HumidityArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_HumidityArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_HumidityArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_HumidityArc, &ui_img_water_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Droplet = lv_img_create(ui_HumidityGroup);
    lv_img_set_src(ui_Droplet, &ui_img_droplet_png);
    lv_obj_set_width(ui_Droplet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Droplet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Droplet, -40);
    lv_obj_set_y(ui_Droplet, 0);
    lv_obj_set_align(ui_Droplet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Droplet, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Droplet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Droplet, 100);

    ui_DropletLabel = lv_label_create(ui_HumidityGroup);
    lv_obj_set_width(ui_DropletLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DropletLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropletLabel, 40);
    lv_obj_set_y(ui_DropletLabel, 0);
    lv_obj_set_align(ui_DropletLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DropletLabel, "70%");
    lv_obj_set_style_text_font(ui_DropletLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Group = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_CO2Group, 160);
    lv_obj_set_height(ui_CO2Group, 100);
    lv_obj_set_x(ui_CO2Group, 0);
    lv_obj_set_y(ui_CO2Group, 100);
    lv_obj_set_align(ui_CO2Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CO2Group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CO2Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CO2Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CO2Group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CO2Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Arc = lv_arc_create(ui_CO2Group);
    lv_obj_set_width(ui_CO2Arc, 80);
    lv_obj_set_height(ui_CO2Arc, 80);
    lv_obj_set_x(ui_CO2Arc, -40);
    lv_obj_set_y(ui_CO2Arc, 0);
    lv_obj_set_align(ui_CO2Arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_CO2Arc, 55);
    lv_obj_set_style_arc_color(ui_CO2Arc, lv_color_hex(0xB3B3E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CO2Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CO2Arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_CO2Arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_CO2Arc, &ui_img_co2_arc_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_CO2 = lv_img_create(ui_CO2Group);
    lv_img_set_src(ui_CO2, &ui_img_co2_png);
    lv_obj_set_width(ui_CO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2, -40);
    lv_obj_set_y(ui_CO2, 0);
    lv_obj_set_align(ui_CO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CO2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CO2, 100);

    ui_CO2Label = lv_label_create(ui_CO2Group);
    lv_obj_set_width(ui_CO2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2Label, 40);
    lv_obj_set_y(ui_CO2Label, 0);
    lv_obj_set_align(ui_CO2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2Label, "1000\nppm");
    lv_obj_set_style_text_font(ui_CO2Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
