// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Environment_sensor

#ifndef _ENVIRONMENT_SENSOR_UI_H
#define _ENVIRONMENT_SENSOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_CalibrationScreen
void ui_CalibrationScreen_screen_init(void);
extern lv_obj_t *ui_CalibrationScreen;
extern lv_obj_t *ui_CalibrateLabel;
void ui_event_CalibrateButton( lv_event_t * e);
extern lv_obj_t *ui_CalibrateButton;
void ui_event_BackButton1( lv_event_t * e);
extern lv_obj_t *ui_BackButton1;
extern lv_obj_t *ui_BackLabel1;
// SCREEN: ui_ConfirmationScreen
void ui_ConfirmationScreen_screen_init(void);
extern lv_obj_t *ui_ConfirmationScreen;
extern lv_obj_t *ui_CalibrateInfo;
void ui_event_CalibrateStart( lv_event_t * e);
extern lv_obj_t *ui_CalibrateStart;
extern lv_obj_t *ui_StartLabel;
extern lv_obj_t *ui_UpdateProgress;
void ui_event_BackButton2( lv_event_t * e);
extern lv_obj_t *ui_BackButton2;
extern lv_obj_t *ui_BackLabel2;
// SCREEN: ui_MainScreen1
void ui_MainScreen1_screen_init(void);
extern lv_obj_t *ui_MainScreen1;
extern lv_obj_t *ui_TempLabel1;
extern lv_obj_t *ui_TempIcon1;
extern lv_obj_t *ui_HumidityLabel1;
extern lv_obj_t *ui_HumidityIcon1;
extern lv_obj_t *ui_CO2Label1;
void ui_event_CO2Icon1( lv_event_t * e);
extern lv_obj_t *ui_CO2Icon1;
extern lv_obj_t *ui_GAP6;
extern lv_obj_t *ui_BatLabel1;
extern lv_obj_t *ui_GAP4;
extern lv_obj_t *ui_GAP5;
extern lv_obj_t *ui_AirLabel;
extern lv_obj_t *ui_ObjectLabel;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_GAP7;
extern lv_obj_t *ui_ObjectTempLabel;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_AmbientTempLabel;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_light_blue_dithered_rotated_png);   // assets\light_blue_dithered_rotated.png
LV_IMG_DECLARE( ui_img_calibrate_png);   // assets\Calibrate.png
LV_IMG_DECLARE( ui_img_thermometer_png);   // assets\Thermometer.png
LV_IMG_DECLARE( ui_img_droplet_png);   // assets\Droplet.png
LV_IMG_DECLARE( ui_img_co2_resize_png);   // assets\CO2_resize.png
LV_IMG_DECLARE( ui_img_point_temperature_png);   // assets\point_temperature.png
LV_IMG_DECLARE( ui_img_ambient_temperature_png);   // assets\ambient_temperature.png

LV_FONT_DECLARE( ui_font_Interbold40);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
