// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Environment_sensor

#include "ui.h"

void Start_calibration(lv_event_t * e)
{
	// Your code here
}

void CalibrateStart(lv_event_t * e)
{
	// Your code here
}
