// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Environment_sensor

#ifndef _ENVIRONMENT_SENSOR_UI_H
#define _ENVIRONMENT_SENSOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Icon_group;
extern lv_obj_t * ui_Droplet;
extern lv_obj_t * ui_Thermometer;
extern lv_obj_t * ui_Text_group;
extern lv_obj_t * ui_TemperatureText;
extern lv_obj_t * ui_HumidityText;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_TemperatureGroup;
void ui_event_TemperatureArc(lv_event_t * e);
extern lv_obj_t * ui_TemperatureArc;
extern lv_obj_t * ui_Thermometer1;
extern lv_obj_t * ui_TemperatureLabel;
extern lv_obj_t * ui_HumidityGroup;
extern lv_obj_t * ui_Droplet1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_TemperatureGroup1;
void ui_event_TemperatureArc1(lv_event_t * e);
extern lv_obj_t * ui_TemperatureArc1;
extern lv_obj_t * ui_Thermometer2;
extern lv_obj_t * ui_TemperatureLabel1;
extern lv_obj_t * ui_TemperatureGroup2;
void ui_event_TemperatureArc2(lv_event_t * e);
extern lv_obj_t * ui_TemperatureArc2;
extern lv_obj_t * ui_Thermometer3;
extern lv_obj_t * ui_TemperatureLabel2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_TemperatureGroup3;
void ui_event_TemperatureArc3(lv_event_t * e);
extern lv_obj_t * ui_TemperatureArc3;
extern lv_obj_t * ui_Thermometer4;
extern lv_obj_t * ui_TemperatureLabel3;
extern lv_obj_t * ui_TemperatureGroup4;
void ui_event_TemperatureArc4(lv_event_t * e);
extern lv_obj_t * ui_TemperatureArc4;
extern lv_obj_t * ui_Thermometer5;
extern lv_obj_t * ui_TemperatureLabel4;
extern lv_obj_t * ui_TemperatureGroup5;
void ui_event_TemperatureArc5(lv_event_t * e);
extern lv_obj_t * ui_TemperatureArc5;
extern lv_obj_t * ui_Thermometer6;
extern lv_obj_t * ui_TemperatureLabel5;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_droplet_png);    // assets\Droplet.png
LV_IMG_DECLARE(ui_img_thermometer_png);    // assets\Thermometer.png
LV_IMG_DECLARE(ui_img_co2_png);    // assets\co2.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
